import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/components/shared/provider";

const inter = Inter({
    subsets: ["cyrillic"],
    variable: "--font-inter",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Chad",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link data-rh="true" rel="icon" href="/logo.svg" />
            </head>
            <body className={inter.className}>
                <main>
                    <Providers>{children}</Providers>
                </main>
            </body>
        </html>
    );
}
